import type { MessageKey } from "../../i18n/translations";

/**
 * Frontend catalog of SponsorGuard reason codes.
 * Keep this aligned with backend `ComplianceReasonCode`.
 */
export const COMPLIANCE_REASON_CODES = [
  "REQUIRED_MENTION_FOUND",
  "REQUIRED_MENTION_MISSING",
  "REQUIRED_TOKEN_FOUND",
  "REQUIRED_TOKEN_MISSING",
  "REQUIRED_MENTION_WITHIN_DEADLINE",
  "REQUIRED_MENTION_TOO_LATE",
  "FORBIDDEN_PHRASE_ABSENT",
  "FORBIDDEN_PHRASE_FOUND",
  "REQUIRED_URL_FOUND",
  "REQUIRED_URL_MISSING",
  "SEMANTIC_REQUIREMENT_CONFIRMED",
  "SEMANTIC_REQUIREMENT_MISSING",
  "SEMANTIC_REQUIREMENT_UNCERTAIN",
  "FORBIDDEN_CLAIM_DETECTED",
  "FORBIDDEN_CLAIM_CLEAR",
  "FORBIDDEN_CLAIM_UNCERTAIN",
  "SEMANTIC_VERIFICATION_UNAVAILABLE",
  "MANUAL_REVIEW_REQUIRED",
] as const;

export type ComplianceReasonCode = (typeof COMPLIANCE_REASON_CODES)[number];

export const COMPLIANCE_REASON_PRIMARY_KEYS = {
  REQUIRED_MENTION_FOUND: "sponsored.reasons.REQUIRED_MENTION_FOUND",
  REQUIRED_MENTION_MISSING: "sponsored.reasons.REQUIRED_MENTION_MISSING",
  REQUIRED_TOKEN_FOUND: "sponsored.reasons.REQUIRED_TOKEN_FOUND",
  REQUIRED_TOKEN_MISSING: "sponsored.reasons.REQUIRED_TOKEN_MISSING",
  REQUIRED_MENTION_WITHIN_DEADLINE: "sponsored.reasons.REQUIRED_MENTION_WITHIN_DEADLINE",
  REQUIRED_MENTION_TOO_LATE: "sponsored.reasons.REQUIRED_MENTION_TOO_LATE",
  FORBIDDEN_PHRASE_ABSENT: "sponsored.reasons.FORBIDDEN_PHRASE_ABSENT",
  FORBIDDEN_PHRASE_FOUND: "sponsored.reasons.FORBIDDEN_PHRASE_FOUND",
  REQUIRED_URL_FOUND: "sponsored.reasons.REQUIRED_URL_FOUND",
  REQUIRED_URL_MISSING: "sponsored.reasons.REQUIRED_URL_MISSING",
  SEMANTIC_REQUIREMENT_CONFIRMED: "sponsored.reasons.SEMANTIC_REQUIREMENT_CONFIRMED",
  SEMANTIC_REQUIREMENT_MISSING: "sponsored.reasons.SEMANTIC_REQUIREMENT_MISSING",
  SEMANTIC_REQUIREMENT_UNCERTAIN: "sponsored.reasons.SEMANTIC_REQUIREMENT_UNCERTAIN",
  FORBIDDEN_CLAIM_DETECTED: "sponsored.reasons.FORBIDDEN_CLAIM_DETECTED",
  FORBIDDEN_CLAIM_CLEAR: "sponsored.reasons.FORBIDDEN_CLAIM_CLEAR",
  FORBIDDEN_CLAIM_UNCERTAIN: "sponsored.reasons.FORBIDDEN_CLAIM_UNCERTAIN",
  SEMANTIC_VERIFICATION_UNAVAILABLE: "sponsored.reasons.SEMANTIC_VERIFICATION_UNAVAILABLE",
  MANUAL_REVIEW_REQUIRED: "sponsored.reasons.MANUAL_REVIEW_REQUIRED",
} as const satisfies Record<ComplianceReasonCode, MessageKey>;

export function isComplianceReasonCode(value: string): value is ComplianceReasonCode {
  return Object.hasOwn(COMPLIANCE_REASON_PRIMARY_KEYS, value);
}
